# Issue Notification Workflow for onboarding requests
name: Issue Notification

on:
  push:
  issues:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    # if: contains(github.event.issue.labels.*.name, 'infrastructure/onboarding')
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/infra/ci/camunda-community-hub/infrastructure SLACK_INFRADRIBOTSTAGE_WEBHOOK_URL
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2
        env:
          COMMUNITY_HUB_VAULT_SECRETS_TF_FILE: https://github.com/camunda/infra-core/blob/stage/terraform/github/prod/camunda-community-hub-vault-secrets.tf
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*New Community Hub Repository Onboarding Request* submission from @${{ github.event.issue.user.login }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*What's your team?*\nCamunda Community Hub"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Category of your request*\nPermissions & Access Control"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Details for your request*\nPlease review the following GitHub issue to onboard a new repository to the Camunda Community Hub and complete the necessary configurations.\nOnce the setup is done, kindly mark the GitHub issue as resolved and inform the requester."
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*GitHub Issue Title*\n${{ github.event.issue.title }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.issue.html_url }}|View Issue #${{ github.event.issue.number }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Action Required*\n<${{ env.COMMUNITY_HUB_VAULT_SECRETS_TF_FILE }}|➜ Add repository in infra-core>"
                  }
                }
              ]
            }
          webhook: ${{ steps.secrets.outputs.SLACK_INFRADRIBOTSTAGE_WEBHOOK_URL }}
          webhook-type: incoming-webhook
